// This file will be auto-generated by Supabase CLI
// For now, we'll use a basic type definition

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      user_progress: {
        Row: {
          id: string
          user_id: string
          level: number
          xp: number
          streak: number
          last_active_date: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          level?: number
          xp?: number
          streak?: number
          last_active_date?: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          level?: number
          xp?: number
          streak?: number
          last_active_date?: string
          created_at?: string
        }
      }
      user_stats: {
        Row: {
          id: string
          user_id: string
          total_sessions: number
          total_questions: number
          topics_completed: number
          study_time: number
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          total_sessions?: number
          total_questions?: number
          topics_completed?: number
          study_time?: number
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          total_sessions?: number
          total_questions?: number
          topics_completed?: number
          study_time?: number
          updated_at?: string
        }
      }
      documents: {
        Row: {
          id: string
          user_id: string
          filename: string
          file_path: string
          file_type: string
          file_size: number
          title: string | null
          subject: string | null
          language: string
          processed: boolean
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          filename: string
          file_path: string
          file_type: string
          file_size: number
          title?: string | null
          subject?: string | null
          language?: string
          processed?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          filename?: string
          file_path?: string
          file_type?: string
          file_size?: number
          title?: string | null
          subject?: string | null
          language?: string
          processed?: boolean
          created_at?: string
        }
      }
      tutoring_sessions: {
        Row: {
          id: string
          user_id: string
          started_at: string
          ended_at: string | null
          duration: number | null
          message_count: number
          topic: string | null
        }
        Insert: {
          id?: string
          user_id: string
          started_at?: string
          ended_at?: string | null
          duration?: number | null
          message_count?: number
          topic?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          started_at?: string
          ended_at?: string | null
          duration?: number | null
          message_count?: number
          topic?: string | null
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      match_documents: {
        Args: {
          query_embedding: number[]
          match_threshold: number
          match_count: number
          user_id: string
        }
        Returns: {
          id: string
          content: string
          similarity: number
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
  }
}
